[build]
  publish = "dist/"
  command = "pnpm run build"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.astro",  # Cache astro node modules to speed up subsequent installs
    ".astro"                # Cache Astro's internal cache directory
  ]